---
--- Name:        eclipse-mk/eclipse-mk_project.lua
--- Purpose:     Generate Eclipse CDT Makefile based '.project' file
--- Author:      Petr Kalandra
--- Created:     2019/02/15
---
	function premake.modules.eclipse_mk.project.generate(prj)

		premake.eol("\r\n")
		premake.indent("\t")
		premake.escaper(premake.modules.eclipse_mk.esc)

		_p('<?xml version="1.0" encoding="UTF-8"?>')
		_p('<projectDescription>')
		_p(1, '<name>%s</name>', prj.name)
		_p(1, '<comment>Generated by Premake5</comment>')
		_p(1, '<projects></projects>')
		_p(1, '<buildSpec>')
		_p(2, 	'<buildCommand>')
		_p(3, 		'<name>org.eclipse.cdt.managedbuilder.core.genmakebuilder</name>')
		_p(3, 		'<triggers>clean,full,incremental,</triggers>')
		_p(3, 		'<arguments></arguments>')
		_p(2, 	'</buildCommand>')
		_p(2, 	'<buildCommand>')
		_p(3, 		'<name>org.eclipse.cdt.managedbuilder.core.ScannerConfigBuilder</name>')
		_p(3, 		'<triggers>full,incremental,</triggers>')
		_p(3, 		'<arguments></arguments>')
		_p(2, 	'</buildCommand>')
		_p(1, '</buildSpec>')
		_p(1, '<natures>')
		_p(2, 	'<nature>org.eclipse.cdt.core.cnature</nature>')
		_p(2, 	'<nature>org.eclipse.cdt.core.ccnature</nature>')
		_p(2, 	'<nature>org.eclipse.cdt.managedbuilder.core.managedBuildNature</nature>')
		_p(2, 	'<nature>org.eclipse.cdt.managedbuilder.core.ScannerConfigNature</nature>')
		_p(1, '</natures>')	
		_p('</projectDescription>')
	end
